name: lint-validate

on:
        push:
                branches:
                        - main

permissions:
        id-token: write
        contents: read

env:
        AZURE_RESOURCEGROUP_NAME: rg-test
        LOCATION: uksouth
        ENVIRONMENT_TYPE: test

jobs:
        lint:
                runs-on: ubuntu-latest
                steps:
                - uses: actions/checkout@v3
                - name: Run Bicep linter
                    run: az bicep build --file ./src/main.bicep

        create-resource-group:
                runs-on: ubuntu-latest
                needs: lint
                steps:
                - uses: actions/checkout@v3
                - uses: azure/login@v1
                    name: Sign in to Azure
                    with:
                        client-id: ${{ secrets.AZURE_CLIENT_ID }}
                        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                - name: Create Resource Group for preflight validation
                    run: az group create --name ${{ env.AZURE_RESOURCEGROUP_NAME }} --location ${{ env.LOCATION }}

        validate:
                runs-on: ubuntu-latest
                needs: [lint, create-resource-group]
                steps:
                - uses: actions/checkout@v3
                - uses: azure/login@v1
                    name: Sign in to Azure
                    with:
                        client-id: ${{ secrets.AZURE_CLIENT_ID }}
                        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                - name: Run preflight validation
                    with:
                        deploymentName: ${{ github.run_number }}
                        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
                        template: ./src/main.bicep
                        parameters: ./src/parameters/main.bicepparam
                        deploymentMode: Validate

        deploy:
                runs-on: ubuntu-latest
                needs: [lint, validate, create-resource-group]
                steps:
                - uses: actions/checkout@v3
                - uses: azure/login@v1
                    name: Sign in to Azure
                    with:
                        client-id: ${{ secrets.AZURE_CLIENT_ID }}
                        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                - name: Deploy DevBox Environment
                    run: |
                        az deployment sub create \
                            --name "GitHub.Actions" \
                            --location "uksouth" \
                            --template-file ./src/main.bicep \
                            --parameters ./src/parameters/main.bicepparam
